name: Java frondend Deployment

on:
  push:
    branches:
      - main
jobs:
  JavaloginPracticeApp:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Update and Install JDK
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          echo "Java Installation Completed"

      - name: Verify Java Installation
        run: |
          java -version
          echo "JAVA_HOME: $JAVA_HOME"

      - name: Set JAVA_HOME
        run: |
          echo "export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" | sudo tee -a /etc/profile
          source /etc/profile
          echo "JAVA_HOME set to: $JAVA_HOME"
          
      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven
          echo "Maven Installation Completed"

      - name: Verify Maven Installation
        run: mvn -version

      - name: Install Maven
        run: |
          sudo apt install -y maven
          echo "Maven Installation Completed"

      - name: Verify Maven Installation
        run: mvn -version

      - name: Build WAR file
        run: mvn clean package
        working-directory: ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WAR-File
          path: target/JavaLoginShowcase-1.0.0.war
  deploy:
    needs: JavaloginPracticeApp
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: WAR-File
          path: ./artifact

      - name: Install SSH & SSHPass
        run: |
          sudo apt update
          sudo apt install -y sshpass

      - name: Install Tomcat on Frontend VM
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.FRONTEND_VM_IP }} << EOF
          sudo apt update
          sudo apt install -y tomcat9 tomcat9-admin tomcat9-common
          sudo systemctl enable tomcat9
          sudo systemctl start tomcat9
          EOF

      - name: Deploy WAR
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no ./artifact/JavaLoginShowcase-1.0.0.war ${{ secrets.SSH_USER }}@${{ secrets.FRONTEND_VM_IP }}:/tmp/
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.FRONTEND_VM_IP }} << EOF
          sudo mv /tmp/JavaLoginShowcase-1.0.0.war /var/lib/tomcat9/webapps/
          sudo chown tomcat:tomcat /var/lib/tomcat9/webapps/JavaLoginShowcase-1.0.0.war
          sudo chmod 644 /var/lib/tomcat9/webapps/JavaLoginShowcase-1.0.0.war
          sudo systemctl restart tomcat9
          EOF
