name: Java frondend Deployment

on:
  push:
    branches:
      - main
jobs:
  JavaloginPracticeApp:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Update and Install JDK
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          echo "Java Installation Completed"

      - name: Verify Java Installation
        run: |
          java -version
          echo "JAVA_HOME: $JAVA_HOME"

      - name: Set JAVA_HOME
        run: |
          echo "export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" | sudo tee -a /etc/profile
          source /etc/profile
          echo "JAVA_HOME set to: $JAVA_HOME"
