name: Java frondend Deployment

on:
  push:
    branches:
      - main
jobs:
  JavaloginPracticeApp:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Update and Install JDK
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          echo "Java Installation Completed"

      - name: Verify Java Installation
        run: |
          java -version
          echo "JAVA_HOME: $JAVA_HOME"

      - name: Set JAVA_HOME
        run: |
          echo "export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" | sudo tee -a /etc/profile
          source /etc/profile
          echo "JAVA_HOME set to: $JAVA_HOME"
          
      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven
          echo "Maven Installation Completed"

      - name: Verify Maven Installation
        run: mvn -version

      - name: Install Maven
        run: |
          sudo apt install -y maven
          echo "Maven Installation Completed"

      - name: Verify Maven Installation
        run: mvn -version

      - name: Build WAR file
        run: mvn clean package
        working-directory: ${{ github.workspace }}/JavaLoginPracticeApp

      # - name: Get Latest Tomcat Version
      #   run: |
      #     TOMCAT_MAJOR=10
      #     TOMCAT_VERSION=$(curl -s https://downloads.apache.org/tomcat/tomcat-$TOMCAT_MAJOR/ | grep -oP '(?<=v)10\.\d+\.\d+' | sort -V | tail -1)
      #     echo "Latest Tomcat Version: $TOMCAT_VERSION"
      #     echo "TOMCAT_VERSION=$TOMCAT_VERSION" >> $GITHUB_ENV

      # - name: Install Apache Tomcat
      #   run: |
      #     TOMCAT_DIR=/opt/tomcat
      #     TOMCAT_URL="https://downloads.apache.org/tomcat/tomcat-10/v${{ env.TOMCAT_VERSION }}/bin/apache-tomcat-${{ env.TOMCAT_VERSION }}.tar.gz"

      #     sudo apt install -y wget unzip
          
      #     echo "Downloading Tomcat from: $TOMCAT_URL"
      #     sudo wget -q $TOMCAT_URL -O /tmp/tomcat.tar.gz || { echo "Download failed! Check the version or URL."; exit 1; }
      #     sudo mkdir -p $TOMCAT_DIR
      #     sudo tar -xvzf /tmp/tomcat.tar.gz -C $TOMCAT_DIR --strip-components=1
          
      #     # Fix permissions
      #     sudo chmod -R 755 $TOMCAT_DIR
      #     sudo chown -R $USER:$USER $TOMCAT_DIR
      #     echo "Apache Tomcat Installed Successfully"

      # - name: Verify Tomcat Installation
      #   run: |
      #     /opt/tomcat/bin/version.sh

      # - name: Start Apache Tomcat
      #   run: |
      #     /opt/tomcat/bin/startup.sh
      #     sleep 5  # Wait for Tomcat to initialize
      #     /opt/tomcat/bin/version.sh  # Check if Tomcat is running
      #     echo "Tomcat Started Successfully"



