name: Java frondend Deployment

on:
  push:
    branches:
      - main
jobs:
  JavaloginPracticeApp:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Update and Install JDK
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          echo "Java Installation Completed"

      - name: Verify Java Installation
        run: |
          java -version
          echo "JAVA_HOME: $JAVA_HOME"

      - name: Set JAVA_HOME
        run: |
          echo "export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" | sudo tee -a /etc/profile
          source /etc/profile
          echo "JAVA_HOME set to: $JAVA_HOME"
          
      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven
          echo "Maven Installation Completed"

      - name: Verify Maven Installation
        run: mvn -version

      - name: Install Apache Tomcat
        run: |
          TOMCAT_VERSION=10.1.16  # Change to your required version
          TOMCAT_DIR=/opt/tomcat
          
          sudo apt install -y wget unzip
          sudo wget https://downloads.apache.org/tomcat/tomcat-10/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz -O /tmp/tomcat.tar.gz
          sudo mkdir -p $TOMCAT_DIR
          sudo tar -xvzf /tmp/tomcat.tar.gz -C $TOMCAT_DIR --strip-components=1
          
          sudo chmod +x $TOMCAT_DIR/bin/*.sh
          echo "Apache Tomcat Installed Successfully"

      - name: Verify Tomcat Installation
        run: |
          /opt/tomcat/bin/version.sh

      - name: Start Apache Tomcat
        run: |
          /opt/tomcat/bin/startup.sh
          echo "Tomcat Started"
